name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Checkout the repository

    # Generates the snake gif and svg files
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: jaswanth-damarla
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Show the status of the build (for debugging)
    - run: git status

    # Push changes to the main branch (instead of the output branch)
    - name: Push changes to main branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # Change this to "main" (or "master" depending on your default branch)
        force: true

    # Optionally, you can also push the changes to the output branch if needed
    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # This will push to the output branch if needed
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
