name: Generate Snake

permissions:
  contents: write  # Ensure the action has write access to the contents of the repository

on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v2

    # Step 2: Generate the snake GIF and SVG
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: jaswanth-damarla
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Step 3: Check the status of the build for debugging
    - run: git status

    # Step 4: Push the changes to the main branch
    - name: Push changes to main branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use default GitHub token (with write permissions)
        branch: main  # Ensure this matches the branch you want to push to
        force: true

    # Step 5: Optionally push to a separate output branch (e.g., if you want to host it as a GitHub Pages site)
    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # The branch where the animated snake files will be pushed
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
